In [1]:
import numpy as np

In [3]:
arr = np.ones((2,3,4,3), dtype='int32')
arr
arr.dtype
type(arr.shape)
arr.ndim
arr.size

array([[[[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]],

        [[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]],

        [[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]]],


       [[[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]],

        [[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]],

        [[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]]]], dtype=int32)

dtype('int32')

tuple

4

72

<h2 style="font-size: 28px; font-weight: bold; margin-bottom: 10px;">📦 Table: Array Creation Functions</h2>
<table style="font-size: 24px; font-weight: bold; border-collapse: collapse; text-align: left; width: 100%;">
  <thead>
    <tr style="border-bottom: 3px solid black;">
      <th style="padding: 12px;">Function</th>
      <th style="padding: 12px;">Input</th>
      <th style="padding: 12px;">Output</th>
      <th style="padding: 12px;">Example</th>
    </tr>
  </thead>
  <tbody>
    <tr style="border-bottom: 1px solid gray;">
      <td style="padding: 12px;">np.array()</td>
      <td style="padding: 12px;">Python list</td>
      <td style="padding: 12px;">ndarray</td>
      <td style="padding: 12px;">np.array([1,2,3])</td>
    </tr>
    <tr style="border-bottom: 1px solid gray;">
      <td style="padding: 12px;">np.zeros()</td>
      <td style="padding: 12px;">shape</td>
      <td style="padding: 12px;">array of 0s</td>
      <td style="padding: 12px;">np.zeros((2,3))</td>
    </tr>
    <tr style="border-bottom: 1px solid gray;">
      <td style="padding: 12px;">np.ones()</td>
      <td style="padding: 12px;">shape</td>
      <td style="padding: 12px;">array of 1s</td>
      <td style="padding: 12px;">np.ones(4)</td>
    </tr>
    <tr style="border-bottom: 1px solid gray;">
      <td style="padding: 12px;">np.arange()</td>
      <td style="padding: 12px;">start, stop, step</td>
      <td style="padding: 12px;">range array</td>
      <td style="padding: 12px;">np.arange(0,10,2) → [0 2 4 6 8]</td>
    </tr>
    <tr style="border-bottom: 1px solid gray;">
      <td style="padding: 12px;">np.linspace()</td>
      <td style="padding: 12px;">start, stop, num</td>
      <td style="padding: 12px;">evenly spaced</td>
      <td style="padding: 12px;">np.linspace(0,1,5) → [0. 0.25 0.5 0.75 1.]</td>
    </tr>
    <tr style="border-bottom: 1px solid gray;">
      <td style="padding: 12px;">np.eye()</td>
      <td style="padding: 12px;">size</td>
      <td style="padding: 12px;">identity matrix</td>
      <td style="padding: 12px;">np.eye(3)</td>
    </tr>
  </tbody>
</table>


In [4]:
x = np.linspace(2,3,5)
x
y = np.zeros(3)
y

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

array([0., 0., 0.])

In [9]:
x = np.random.randint(1, 10, 5)
x
x[-1]

array([2, 8, 4, 6, 7], dtype=int32)

np.int32(7)

In [21]:
a = [i for i in range(0,100, 4)]
b = np.linspace(0,50,100)
a = np.array(a)


In [20]:
a
b = [f"{x:.4f}" for x in b]
b

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64,
       68, 72, 76, 80, 84, 88, 92, 96])

['0.0000',
 '0.5051',
 '1.0101',
 '1.5152',
 '2.0202',
 '2.5253',
 '3.0303',
 '3.5354',
 '4.0404',
 '4.5455',
 '5.0505',
 '5.5556',
 '6.0606',
 '6.5657',
 '7.0707',
 '7.5758',
 '8.0808',
 '8.5859',
 '9.0909',
 '9.5960',
 '10.1010',
 '10.6061',
 '11.1111',
 '11.6162',
 '12.1212',
 '12.6263',
 '13.1313',
 '13.6364',
 '14.1414',
 '14.6465',
 '15.1515',
 '15.6566',
 '16.1616',
 '16.6667',
 '17.1717',
 '17.6768',
 '18.1818',
 '18.6869',
 '19.1919',
 '19.6970',
 '20.2020',
 '20.7071',
 '21.2121',
 '21.7172',
 '22.2222',
 '22.7273',
 '23.2323',
 '23.7374',
 '24.2424',
 '24.7475',
 '25.2525',
 '25.7576',
 '26.2626',
 '26.7677',
 '27.2727',
 '27.7778',
 '28.2828',
 '28.7879',
 '29.2929',
 '29.7980',
 '30.3030',
 '30.8081',
 '31.3131',
 '31.8182',
 '32.3232',
 '32.8283',
 '33.3333',
 '33.8384',
 '34.3434',
 '34.8485',
 '35.3535',
 '35.8586',
 '36.3636',
 '36.8687',
 '37.3737',
 '37.8788',
 '38.3838',
 '38.8889',
 '39.3939',
 '39.8990',
 '40.4040',
 '40.9091',
 '41.4141',
 '41.9192',
 '42.4242',


In [30]:
for x in b:
    print(f"{x:.4f}")
b

ValueError: Unknown format code 'f' for object of type 'str'