In [1]:
import numpy as np

arr_0d = np.array(25)
print('0-D:', arr_0d)

arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print('2-D:\n', arr_2d)

arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print('3-D:\n', arr_3d)


0-D: 25
2-D:
 [[1 2 3]
 [4 5 6]]
3-D:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [2]:
# Creating random arrays
arr = np.array([1, 2, 3, 4])
zeros_arr = np.zeros((2, 3))
ones_arr = np.ones((3, 2))
random = np.random.rand(2, 2, 2)
arange_arr = np.arange(0, 12, 2)
linspace_arr = np.linspace(0, 1, 5)
copy_arr = random.copy()


print('array:\n', arr)
print('Zeros:\n', zeros_arr)
print('Ones:\n', ones_arr)
print('Arange:\n', arange_arr)
print('Linspace:', linspace_arr)

print(f"3D Array with Random Numbers (2x2x2):\n{random}")
print('\nCopy:\n', copy_arr)


array:
 [1 2 3 4]
Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
Arange:
 [ 0  2  4  6  8 10]
Linspace: [0.   0.25 0.5  0.75 1.  ]
3D Array with Random Numbers (2x2x2):
[[[0.92798502 0.15818115]
  [0.0568834  0.96130159]]

 [[0.39750751 0.53335796]
  [0.00490365 0.23462697]]]

Copy:
 [[[0.92798502 0.15818115]
  [0.0568834  0.96130159]]

 [[0.39750751 0.53335796]
  [0.00490365 0.23462697]]]
