In [1]:
import numpy as np

In [5]:
img = np.block([
    [[np.ones((2,3))], [np.zeros((2,3))]],
    [[np.zeros((2,3))], [np.ones((2,3))]]
])

In [6]:
img

array([[[1., 1., 1.],
        [1., 1., 1.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [7]:
img = np.block([
    [np.ones((2, 2)), np.zeros((2, 3))],
    [np.zeros((2, 3)), np.ones((2, 2))]
])
print(img)

[[1. 1. 0. 0. 0.]
 [1. 1. 0. 0. 0.]
 [0. 0. 0. 1. 1.]
 [0. 0. 0. 1. 1.]]
