In [4]:
import numpy as np

In [8]:
a = np.array([1,2,3,4])
print(a)
b = np.ones((3,4,5), dtype='int32')

[1 2 3 4]


In [7]:
ch = np.array([['a', 'b', 'c'],['d', 'e', 'f']])
print(ch)

[['a' 'b' 'c']
 ['d' 'e' 'f']]


In [9]:
x = np.arange(30)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [13]:
x.reshape(6,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [14]:
np.random.rand(4,5)

array([[0.91598956, 0.26230735, 0.32191725, 0.04469275, 0.6710496 ],
       [0.06306238, 0.01213051, 0.57008305, 0.168745  , 0.29528332],
       [0.89964172, 0.06610599, 0.82056418, 0.18813931, 0.57541963],
       [0.74506521, 0.8462558 , 0.89843154, 0.46804161, 0.55902381]])

In [16]:
y=np.random.randint(10, size=(6,7))
y

array([[5, 2, 3, 5, 4, 9, 6],
       [8, 4, 6, 5, 5, 9, 2],
       [1, 3, 5, 4, 0, 7, 9],
       [8, 0, 6, 7, 2, 8, 0],
       [2, 3, 5, 4, 8, 3, 4],
       [3, 1, 4, 5, 4, 1, 2]], dtype=int32)